<?php

namespace app\mall\controller;

use think\Controller;
use think\Request;
use think\Db;


class MobileGuest extends Controller {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 请求实例
        $request = Request::instance();
        $params = $request->param();

        // 接受参数部分
        $data = array(
            'e_id' => $params['e_id'],                                            // 页面接收传来的e_id
            'is_del' => 0,                                                    // 在服务期内，没有被删除的企业
        );
        if (empty ($data ['e_id'])) $this->redirect('Home/Tip/bindEID');        // 如果页面没有接收到e_id，则直接输出请绑定一个ID号
        // 校验企业部分
        $einfo = Db::table('t_enterpriseinfo')->where($data)->find();
        if (!$einfo) $this->redirect('Home/Tip/bindEID');                        // 如果企业编号错误，或者企业已经被删除，直接跳转错误页面（2014/11/13 03:10:25
        // 组装信息部分
        $einfo ['e_index_logo'] = assemblepath($einfo ['e_index_logo'], true);    // 组装路径：2015/10/02 20:40:30，企业主业logo
        $einfo ['e_square_logo'] = assemblepath($einfo ['e_square_logo'], true); // 组装路径：2014/09/17 20:40:30，使用绝对路径供分享用
        $einfo ['e_rect_logo'] = assemblepath($einfo ['e_rect_logo'], true);    // 组装路径：2014/09/17 20:40:30
        $einfo ['qr_code'] = assemblepath($einfo ['qr_code'], true);            // 组装路径：2015/10/02 20:40:30，企业二维码
        // 推送信息部分
        $this->assign("enterprise", $einfo);// 始终推送到前台
        $this->assign("einfo", $einfo);// 子类使用父类的$this->einfo企业信息变量（以后打算不用enterprise）
        $this->assign("e_id", $data['e_id']);// 推送e_id到前台，保留传统简洁风格（除非页面更改，否则必须有这个参数，后面的可能要用）

        // 从cookie中获取sso_token
        $this->assign("sso_token", cookie('sso_token'));
    }

}